trigger:
- master

resources:
- repo: self

name: 
stages:

- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '5.0.100-rc.2.20479.15' 

    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        testRunTitle: 'TestUniter'
        workingDirectory: '.\tests\Fibonacci.Tests'
         